# Generated by Django 5.0.2 on 2024-02-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='otp_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
