# Generated by Django 5.0 on 2024-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlapp', '0002_custom_user_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
